In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns

from google.colab import drive

In [ ]:
drive.mount("/content/gdrive")

Mounted at /content/gdrive

In [ ]:
mask_na = df_1.isna()
df_concat = pd.concat([df_2, df_3])
by_row_index = df_concat.groupby(df_concat.index)
df_means = by_row_index.mean()

df_clean = df_1.fillna(df_means)

In [ ]:
df_default_risk = pd.read_excel(r"/content/drive/MyDrive/EFI/Data/Sample 2007-2017/Merton Distance to Defaults  _all data.xlsx")
df_price_eqy = pd.read_excel(r"/content/drive/MyDrive/EFI/Data/Sample 2007-2017/Price_EQY.xlsx")
df_price_energy = pd.read_excel(r"/content/drive/MyDrive/EFI/Data/Sample 2007-2017/Price_Energy.xlsx") #A faire
df_final_sample = pd.read_excel(r"/content/drive/MyDrive/EFI/Data/Sample 2007-2017/Final Sample.xlsx") #A faire
df_carbone_credit_risk = pd.read_excel(r"/content/drive/MyDrive/EFI/Data/Sample 2007-2017/data_Carbone_CreditRisk.xlsx")

In [ ]:
df_default_risk = pd.read_excel(r"/content/drive/MyDrive/EFI/Data/Sample 2017-2022/Merton Distance to default - days=all.xlsx")
df_price_eqy = pd.read_excel(r"/content/drive/MyDrive/EFI/Data/Sample 2017-2022/Price_EQY Sample 2.xlsx")
df_carbone_credit_risk = pd.read_excel(r"/content/drive/MyDrive/EFI/Data/Sample 2017-2022/data_Carbone_CreditRisk.xlsx")

In [ ]:
df_carbon_emission1 = pd.read_excel(r"/content/drive/MyDrive/EFI/Data/Sample 2017-2022/data_Carbone_CreditRisk.xlsx", sheet_name=3)
df_carbon_emission2 = pd.read_excel(r"/content/drive/MyDrive/EFI/Data/Sample 2017-2022/data_Carbone_CreditRisk.xlsx", sheet_name=4)
df_carbon_emission3 = pd.read_excel(r"/content/drive/MyDrive/EFI/Data/Sample 2017-2022/data_Carbone_CreditRisk.xlsx", sheet_name=5)

In [ ]:
df_market_cap = pd.read_excel(r"/content/gdrive/MyDrive/EFI/Data/Sample 2017-2022/data_Carbone_CreditRisk.xlsx", sheet_name="Debt Ratio")

In [ ]:
df_carbon_emission1 = pd.read_excel(r"/content/drive/MyDrive/EFI/Data/Sample 2017-2022/data_Carbone_CreditRisk.xlsx", sheet_name=3)

In [ ]:
df_clean = df_carbon_emission1.iloc[2:]
df_clean.columns = df_clean.iloc[0]
df_clean = df_clean.iloc[1:]
df_clean = df_clean.rename(columns={"Final EQY TICKER" : "Date"})
df_clean["Date"] = pd.to_datetime(df_clean["Date"])
df_clean = df_clean.T.drop_duplicates().T
columns_numerical = df_clean.select_dtypes(exclude="datetime64[ns]").columns.values.tolist()
for col in columns_numerical:
  #df_clean[col] = df_clean[col].apply(pd.to_numeric, errors="coerce").multiply(1000)
  df_clean[col] = df_clean[col].astype("float")#.apply(lambda x: x*1000)

df1 = df_clean.copy(deep=True)

In [ ]:
df_clean.to_excel(r"/content/gdrive/MyDrive/EFI/Clean Data/Sample 2017-2022/Debt Ratio.xlsx", index=False)
df_clean = pd.melt(df_clean, id_vars="Date").rename(columns={2: "Ticker"})
df_clean.to_excel(r"/content/gdrive/MyDrive/EFI/Clean Data/Sample 2017-2022/Melted Debt Ratio.xlsx", index=False)

In [ ]:
price = pd.read_excel(r"/content/gdrive/MyDrive/EFI/Data/Sample 2017-2022/Price_Energy.xlsx")

In [ ]:
df_clean = price.iloc[1:]
df_clean.columns = df_clean.iloc[0]
df_clean = df_clean.iloc[1:]
df_clean = df_clean.T.drop_duplicates().T

In [ ]:
df_clean = df_clean.rename(columns={"CO1 Comdty" : "Oil", "NG1 COMB Comdty": "Natural Gas"})
df_clean["PX_LAST"] = pd.to_datetime(df_clean["PX_LAST"])
columns_numerical = df_clean.select_dtypes(exclude="datetime64[ns]").columns.values.tolist()
for col in columns_numerical:
  #df_clean[col] = df_clean[col].apply(pd.to_numeric, errors="coerce").multiply(1000)
  df_clean[col] = df_clean[col].astype("float")#.apply(lambda x: x*1000)

In [ ]:
df_clean.to_excel(r"/content/gdrive/MyDrive/EFI/Clean Data/Sample 2017-2022/Price Energy.xlsx", index=False)
df_clean = pd.melt(df_clean, id_vars="PX_LAST").rename(columns={1: "Commodity"})
df_clean.to_excel(r"/content/gdrive/MyDrive/EFI/Clean Data/Sample 2017-2022/Melted Price Energy.xlsx", index=False)

In [ ]:
df_std = df_clean.copy(deep=True)
df_std[columns_numerical] = df_clean.rolling(window=252).std()

In [ ]:
df_std.to_excel(r"/content/gdrive/MyDrive/EFI/Clean Data/Sample 2007-2017/Volatility.xlsx", index=False)
df_std = pd.melt(df_std, id_vars="PX_LAST").rename(columns={2: "Ticker"})
#df_std.to_excel(r"/content/gdrive/MyDrive/EFI/Clean Data/Sample 207-2017/Melted Volatility.xlsx", index=False)

In [ ]:
df_clean = df_carbon_emission1.iloc[2:]
df_clean.columns = df_clean.iloc[0]
df_clean = df_clean.iloc[1:]
df_clean = df_clean.rename(columns={"Final EQY TICKER" : "Date"})
df_clean["Date"] = pd.to_datetime(df_clean["Date"]).dt.year
df_clean = df_clean.T.drop_duplicates().T
df_clean = df_clean.drop_duplicates()
columns_numerical = df_clean.select_dtypes(exclude="datetime64[ns]").columns.values.tolist()
for col in columns_numerical:
  #df_clean[col] = df_clean[col].apply(pd.to_numeric, errors="coerce").multiply(1000)
  df_clean[col] = df_clean[col].astype("float")#.apply(lambda x: x*1000)
df1 = df_clean.copy(deep=True)

df_clean = df_carbon_emission2.iloc[2:]
df_clean.columns = df_clean.iloc[0]
df_clean = df_clean.iloc[1:]
df_clean = df_clean.rename(columns={"Final EQY TICKER" : "Date"})
df_clean["Date"] = pd.to_datetime(df_clean["Date"]).dt.year
df_clean = df_clean.T.drop_duplicates().T
df_clean = df_clean.drop_duplicates()
columns_numerical = df_clean.select_dtypes(exclude="datetime64[ns]").columns.values.tolist()
for col in columns_numerical:
  #df_clean[col] = df_clean[col].apply(pd.to_numeric, errors="coerce").multiply(1000)
  df_clean[col] = df_clean[col].astype("float")#.apply(lambda x: x*1000)
df2 = df_clean.copy(deep=True)

df_clean = df_carbon_emission3.iloc[2:]
df_clean.columns = df_clean.iloc[0]
df_clean = df_clean.iloc[1:]
df_clean = df_clean.rename(columns={"Final EQY TICKER" : "Date"})
df_clean["Date"] = pd.to_datetime(df_clean["Date"], format="%Y").dt.year
df_clean = df_clean.T.drop_duplicates().T
df_clean = df_clean.drop_duplicates()
columns_numerical = df_clean.select_dtypes(exclude="datetime64[ns]").columns.values.tolist()
for col in columns_numerical:
  #df_clean[col] = df_clean[col].apply(pd.to_numeric, errors="coerce").multiply(1000)
  df_clean[col] = df_clean[col].astype("float")#.apply(lambda x: x*1000)
df3 = df_clean.copy(deep=True)

In [ ]:
df2 = pd.read_excel(r"/content/drive/MyDrive/EFI/Clean Data/Classeur3.xlsx")
df3 = pd.read_excel(r"/content/drive/MyDrive/EFI/Clean Data/Classeur4.xlsx")

In [ ]:
df1 = df1.reset_index(drop=True)
df3 = df3.reset_index(drop=True)

In [ ]:
df1

2,Date,VIG AV Equity,EBS AV Equity,AST AU Equity,LLOY LN Equity,WBC AU Equity,RY CN Equity,AAPL US Equity,KO US Equity,QAN AU Equity,...,DUK US Equity,DELL US Equity,DOW US Equity,CTVA US Equity,EXPN LN Equity,030200 KS Equity,PPL US Equity,017670 KS Equity,SRE US Equity,GGBR4 BZ Equity
3,2006-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,951.4451,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2007-12-31,NaN,NaN,NaN,2.2021,0.1914,NaN,NaN,NaN,808.0694,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2008-12-31,NaN,0.1180,NaN,2.2483,0.3025,0.8942,NaN,NaN,828.9788,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2009-12-31,NaN,0.1180,155.1252,1.7358,0.3025,1.0070,NaN,NaN,853.1295,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1270.6637,NaN
7,2010-12-31,NaN,0.1180,155.1252,1.3884,0.2133,0.9326,0.1573,NaN,853.1295,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1099.6335,NaN
8,2012-03-31,NaN,0.1180,155.1252,1.5981,0.2865,0.8526,0.1030,NaN,797.1254,...,9899.8555,NaN,NaN,NaN,NaN,NaN,NaN,NaN,807.0945,NaN
9,2013-03-31,NaN,0.1180,119.6224,1.3085,0.2761,0.8906,0.2782,53.1401,781.2036,...,6927.1810,NaN,NaN,NaN,NaN,NaN,NaN,NaN,798.1756,NaN
10,2014-03-31,NaN,0.1180,102.4669,2.1755,0.2927,0.8361,0.3103,47.6318,750.4169,...,5469.8541,NaN,NaN,NaN,1.0744,NaN,NaN,NaN,719.9015,NaN
11,2015-03-31,NaN,0.1180,102.4669,2.0581,0.2730,0.5924,0.1202,33.2282,740.2188,...,5593.0072,NaN,NaN,NaN,0.9979,NaN,NaN,NaN,607.1590,NaN
12,2016-03-31,NaN,2.8779,104.3002,2.3388,0.2950,0.4973,0.1592,33.2282,745.0926,...,4520.6294,NaN,NaN,NaN,1.0385,0.0019,3961.7031,0.0005,801.4857,NaN
13,2017-03-31,NaN,2.5691,109.1305,2.0417,0.2473,0.4926,0.1981,17.3044,762.7951,...,4314.1011,0.9813,NaN,NaN,1.0150,0.0018,3850.1797,0.0004,461.5536,NaN
14,2018-03-31,NaN,3.2545,109.0758,2.0667,0.2565,0.4195,0.2055,11.0626,723.5054,...,4096.8979,0.6705,NaN,NaN,0.8508,0.0018,3838.7808,0.0004,529.0456,NaN
15,2019-03-31,NaN,2.8057,111.6524,2.1475,0.2489,0.3676,0.1943,20.6167,683.8139,...,3937.3232,0.6511,NaN,NaN,0.7406,0.0016,3804.5473,0.0005,593.9418,NaN
16,2020-03-31,1.5275,2.9686,106.6303,1.8012,0.2468,0.3805,0.1728,18.4511,650.6713,...,3409.9246,0.6294,642.5927,NaN,0.5793,0.0015,3456.2491,0.0004,481.8229,228.4461
17,2021-03-31,1.3244,2.6738,106.6303,1.9707,0.2921,0.3632,0.1509,24.0340,541.2673,...,3157.5835,0.5181,731.6693,32.3556,0.4095,0.0015,4583.5038,0.0004,592.1504,209.9391
18,2022-03-31,1.3430,2.2146,NaN,1.7596,NaN,NaN,NaN,14.3710,541.2673,...,3114.2168,0.5181,514.6631,26.1258,0.3976,0.0015,4571.3298,0.0004,531.7275,127.6877

In [ ]:
col1 = df1.select_dtypes(exclude="datetime64[ns]")
col2 = df3.select_dtypes(exclude="datetime64[ns]")
inter_col = set(col1).intersection(col2)

In [ ]:
mean_ratio = (df3[inter_col]/df1[inter_col]).mean()

In [ ]:
df_completed = df1[inter_col].fillna(df3[inter_col]/mean_ratio)
df_completed["Date"] = df1["Date"]

In [ ]:
df_completed.to_excel(r"/content/drive/MyDrive/EFI/Clean Data/Sample 2017-2022/Merged Carbon Intensity.xlsx", index=False)
df_completed = pd.melt(df_completed, id_vars="Date").rename(columns={2 : "Ticker"})
df_completed.to_excel(r"/content/drive/MyDrive/EFI/Clean Data/Sample 2017-2022/Merged Melted Carbon Intensity.xlsx", index=False)

In [ ]:
data = pd.read_excel(r"/content/drive/MyDrive/EFI/Data/Sample 2007-2017/Final Sample.xlsx")

In [ ]:
data["Country"].unique()

array(['AUSTRALIA', 'FRANCE', 'UNITED STATES', 'NETHERLANDS', 'BRITAIN',
       'ITALY', 'BELGIUM', 'CANADA', 'GERMANY', 'SPAIN', 'SWITZERLAND',
       'JAPAN', 'SINGAPORE', 'MEXICO', 'BERMUDA', 'SWEDEN', 'IRELAND',
       'THAILAND', 'CHILE', 'DENMARK', 'INDIA', 'HONG KONG', 'NORWAY',
       'AUSTRIA', 'MALAYSIA', 'CHINA', 'HUNGARY', 'NEW ZEALAND',
       'FINLAND', 'RUSSIA', 'SOUTH AFRICA', 'SOUTH KOREA', 'BRAZIL'],
      dtype=object)

In [ ]:
(data["Country"] == "CHINA").sum()/len(data["Country"])

0.004434589800443459